change leaflet basemap
acep-uaf/aetr-web-book-2024 pull request #110
Opened 2024-09-05 16:19 UTC by ianalexmac

2024-09-09 18:25 UTC, eldobbins commented
The change looks nice in your fork and I don't see anything weird in the code.  Wondering about why you chose to go with an ESRI map base?  Would now be the time to consider Mapbox or would that be too large a diversion?

2024-09-09 18:27 UTC, eldobbins requested changes
Could you add a note in the description saying why you are changing from the USGS map to one that looks like it is distributed by ESRI?

2024-09-09 22:36 UTC, ianalexmac commented
I was unimpressed with the label quality on the USGS basemap, so switched over to a similar one from ESRI. I'm not sure the difference is all that big, but seems to be a little better.

Currently the map is built in Leaflet, which is just fine for our current purposes. I know we are making moves towards Mapbox, but I'm not sure translating from Leaflet to Mapbox is worth the while for this iteration. Let's make the switch on our next go-around.

2024-09-10 17:46 UTC, eldobbins approved these changes

2024-09-10 17:46 UTC, merged